config/routes.rb
Rails.application.routes.draw do
  resources :replies
  resources :reviews
  resources :userbookings
  resources :conversations
  resources :messages
  resources :lessons
  resources :languageskills
  resources :profiles
  resources :notifications
  devise_for :users
  put '/userbookings/completelesson/:id', to: 'userbookings#completelesson'
  root to: 'pages#landing'
  get '/browse', to: 'pages#index'
  get '/browse/lessons', to: 'pages#browse_lessons'
  post '/browse/lessons', to: 'pages#browse_lessons'
  get '/browse/teachers', to: 'pages#browse_teachers'
  post '/browse/teachers', to: 'pages#browse_teachers'
  get '/userbookings/:id/review', to: 'reviews#new'
  resources :charges
  get '/finances', to: 'profiles#finances'
  post '/profile/:id/delist-lesson', to: 'profiles#delist_lesson'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user, optional: true
  has_one_attached :uploaded_image
  has_one_attached :background_image
  has_many :languageskills, dependent: :destroy

  validates :firstname, :lastname, :bio, :skypename, :presence => {:message => "Please fill out this field"}

  def update_average_rating
    set_average_rating
  end

  private
  def set_average_rating
    teacher = User.find(self.user_id)
    userbookings_with_review = 0
    total_stars = 0
    teacher.lessons.each do |lesson|
      lesson.userbookings.each do |userbooking|
        if(userbooking.review)
          userbooking_stars = userbooking.review.stars
          total_stars += userbooking_stars
          userbookings_with_review += 1
        end
      end
    end
    if(userbookings_with_review != 0)
      self.average_rating = ((total_stars / (userbookings_with_review * 5.0)) * 5).round
      self.save!
    end
  end
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy, :delist_lesson]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    authorize(Profile)
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    authorize(Profile)
    @user_reviews = user_reviews(@user)
  end

  # GET /profiles/new
  def new
    authorize(Profile)
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
    authorize(Profile)
  end

  # POST /profiles
  # POST /profiles.json
  def create
    authorize(Profile)
    @profile = Profile.new(profile_params)
    @profile.save!
    # @profile.user.role = Role.find(:role_id)
    if @profile.uploaded_image.attached? == false
      set_default_profile_image(@profile)
    end

    if @profile.background_image.attached? == false
      set_default_background_image(@profile)
    end
   
    if @profile
    redirect_to new_languageskill_path(:profile_id => @profile.id)
    end
  end
 
  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    authorize(Profile)
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile}
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    authorize(Profile)
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url}
      format.json { head :no_content }
    end
  end

  def finances
    if current_user.role.privilege == "teacher"
      @user_transactions = [] 
      current_user.lessons.each do |lesson|
        lesson.userbookings.each do |userbooking|
          @user_transactions << userbooking
        end
      end
    else
      @user_transactions = []
      current_user.userbookings.each do |booking|
        @user_transactions << booking
      end
    end
    
  end

  def delist_lesson
    authorize(Profile)
    @lesson = Lesson.find(params[:lesson_id])
    if @lesson.user_id == current_user.id
      @lesson.delist = true
      @lesson.save
    end
    redirect_to @profile
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = @profile.user
    end
    
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:user_id, :firstname, :lastname, :bio, :skypename, :uploaded_image, :background_image, :average_rating, :role)
    end

    def set_default_profile_image(profile)
          profile.uploaded_image.attach(io: File.open('app/assets/images/default-user-img.png'), filename: 'default-user-img.png')
    end

    def set_default_background_image(profile)
      profile.background_image.attach(io: File.open('app/assets/images/background-image.jpg'), filename: 'background-image.jpg')
    end
  
    def user_reviews(user) 
        userbookings = []
        user.lessons.each do |lesson|
          lesson.userbookings.each do |userbooking|
              userbookings << userbooking
          end
        end
        reviews = []
        userbookings.each do |userbooking|
          if userbooking.review
            reviews << userbooking.review
          end
        end
        return reviews
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :user_id, value: "#{current_user.id}" %>
  </div>

  <div class="field">
    <%= form.label "First name", :class => "labels" %>
    <%= form.text_field :firstname, :class => "textbox", :required => true %>
  </div>

  <div class="field">
    <%= form.label "Last name", :class => "labels" %>
    <%= form.text_field :lastname, :class => "textbox", :required => true %>
  </div>

  <div class="field">
    <%= form.label :bio, :class => "labels"%>
    <%= form.text_area :bio, :class => "resizable-textboxes", :placeholder => "Write a short bio here", :required => true %>
  </div>

  <div class="field">
    <%= form.label :skypename, :class => "labels" %>
    <%= form.text_field :skypename, :class => "textbox", :required => true %>
  </div>

  <div class="field">
    <%= form.label "Profile picture", :class => "labels" %>
    <%= form.file_field :uploaded_image %>
  </div>

   <div class="field">
    <%= form.label "Profile background", :class => "labels" %>
    <%= form.file_field :background_image %>
  </div>

  <div class="submit-actions">
    <%= form.submit 'submit profile', :id => "submit-button" %>
  </div>
<% end %>

app/views/profiles/_lessons_profile.html.erb
<div id="profile-sub-menu">
    <%= link_to '<i class="fas fa-user-graduate"></i> &nbsp; lessons'.html_safe, profile_path, :class => "sub-menu-btn active" %>
    <%= link_to '<i class="fas fa-check-circle"></i> &nbsp; reviews'.html_safe, profile_path(:reviews => 1), :class => "sub-menu-btn" %>
</div>

<% if @user.role.privilege == "teacher" %>
    <% @user.lessons.each do |lesson|%>
        <%if lesson.delist != true %>
            <div class="profile-card">
            <div class="profile-card-row profile-card-title">
                <h2> <%= lesson.languageskill.language_name %> <span style="text-transform: lowercase;"> with </span> <%= lesson.user.profile.firstname %> </h2>
            </div>
            <div class="profile-card-row profile-card-lesson-stats">
                <span> <%= lesson[:duration] %> minutes | $<%= lesson[:price] %> | <%= lesson[:maxbooking] %> available </span>
            </div>
            <div class="profile-card-row profile-card-description-title">
                <h3> lesson description </h3>
            </div>
            <div class="profile-card-row profile-card-lesson-description">
                <span> <%= lesson[:description] %> </span>
            </div>
            <div class="profile-card-row profile-card-teacher">
                <div class="profile-card-teacher-image"> <%= image_tag lesson.user.profile.uploaded_image %> </div>
                <div class="profile-card-teacher-name"> <%= @profile.firstname %> <%= @profile.lastname %> </div>
            </div>
            <% if current_user.role.privilege != "teacher" %>
                <div class="profile-card-row profile-card-book-btn">
                    <%= link_to 'book now', new_userbooking_path(:lesson_id => lesson[:id]), class: "book-btn" %>
                </div> 
            <%elsif current_user.profile.id == @profile.id%>
                <div class="profile-card-row profile-card-delist-btn">
                    <%= link_to 'delist lesson', "/profile/#{@profile.id}/delist-lesson?lesson_id=#{lesson.id}", data: {confirm: "Are you sure you want to remove this lesson?"}, :method => :post, :class => "book-btn", :id => 'delist-btn'%>
                </div>
            <% end %>
            </div>
        <% end %>
    <% end %>
<% end %>

app/views/profiles/_reviews_profile.html.erb
<div id="profile-sub-menu">
    <%if @user.role.privilege == "teacher"%>
    <%= link_to '<i class="fas fa-user-graduate"></i> &nbsp; lessons'.html_safe, profile_path, :class => "sub-menu-btn" %>
    <%= link_to '<i class="fas fa-check-circle"></i> &nbsp; reviews'.html_safe, profile_path(:reviews => 1), :class => "sub-menu-btn active" %>
    <%end%>
</div>

<% @user_reviews.each do |review| %>
    <div class="profile-review-card">
        <div class="profile-card-row">
        <div class="profile-card-column-title">
            <div class="profile-card-row profile-card-review-title">
            <h2> <%= review.userbooking.lesson.languageskill.language_name %> <span style="text-transform: lowercase;"> with </span> <%= @user.profile.firstname %> | <%= review.userbooking.lesson.duration %> minutes</h2>
            </div>
        </div>
        </div>
        <div class="profile-card-row-review">
        <div class="profile-card-teacher-image">
            <%= image_tag review.userbooking.user.profile.uploaded_image.service_url %>
        </div>
        <div class="profile-card-review-column-title">
            <div class="profile-card-row profile-card-reviews-title">
            <span style="font-style: italic;"> Lesson Review </span> <span style="text-transform: lowercase; font-style: italic;">&nbsp;by&nbsp;</span> <span> <%= review.userbooking.user.profile.firstname %> </span>
            </div>
            <div class="profile-card-row profile-card-reviews-body">
            <span> <%= review.content %> </span>
            </div>
        </div>
        </div>
        <% if review.reply %>
            <div class="profile-card-row-review">
            <div class="profile-card-teacher-image">
                <%= image_tag @user.profile.uploaded_image.service_url %>
            </div>
            <div class="profile-card-review-column-title">
                <div class="profile-card-row profile-card-reviews-title">
                <span style="font-style: italic;"> reply</span> <span style="text-transform: lowercase; font-style: italic;">&nbsp;by&nbsp;</span> <span> <%= profile.firstname%> </span>
                </div>
                <div class="profile-card-row profile-card-reviews-body">
                <span> <%= review.reply.content  %></span>
                </div>
            </div>
            </div>
        <% end %>
    </div>
<% end %>

app/views/profiles/_student_about_me.html.erb
<div id="profile-sub-menu">
    <a id="" class="sub-menu-btn student-about-me active"> 
        <span> <i class="fas fa-info-circle"></i> About <%= @profile.firstname %> </span> 
    </a>
</div>
<div class="profile-section-student"> 
    <div class="student-about-me">
        <div> <%= @profile.bio %> </div>
    </div>    
</div>

app/views/profiles/edit.html.erb
<head>
  <title>Home | Chatr</title>
  <link rel="icon" type="image/png" href="">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>

<body>
  <% if current_user %>
    <%= render '/pages/header_nav_authenticated' %>
  <% else %>
    <%= render '/pages/header_nav_public' %>
  <% end %>

  <div id="body" class="outer-wrapper">
    <div class="inner-wrapper">
      
      <%# PUT YOUR CONTENT HERE - THIS CONTAINER IS 1200px WIDE WITH 10px of PADDING LEFT AND RIGHT %>
        <div class= "formbox">
            <div class= "formcontent">
                <h1 id="formtitle">Editing Profile</h1>

                <div class="formfields">
                    <%= render 'form', profile: @profile %>
                </div>
            </div>
        </div>
    </div>
      
  </div>

  <%= render "pages/footer_public" %>
</body>

app/views/profiles/finances.html.erb
<head>
  <title>Home | Chatr</title>
  <link rel="icon" type="image/png" href="">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>

<body>
  <% if current_user %>
    <%= render '/pages/header_nav_authenticated' %>
  <% else %>
    <%= render '/pages/header_nav_public' %>
  <% end %>

  <div id="body" class="outer-wrapper">
    <div class="inner-wrapper">
      
            <%# PUT YOUR CONTENT HERE - THIS CONTAINER IS 1200px WIDE WITH 10px of PADDING LEFT AND RIGHT %>
        <% total_money = 0 %>
        <% @user_transactions.each do |transaction| %>
                <% total_money += transaction.amountpaid  %>
        <% end %>

        <div class="financeswrapper">
        <div class = "earningsheader">
            <% if current_user.role.privilege == "teacher" %>
                <h1> You have earnt $<%= total_money %> </h1>
            <% else %>
                <h1> You have spent $<%= total_money %> </h1>
            <% end %>
        </div>


        <table id="finances">
            <h3>Your Transaction History: </h3>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Language</th>
                    <th>Duration</th>
                    <% if current_user.role.privilege == "teacher" %>
                        <th>From</th>
                    <% else %>
                        <th>To</th>
                    <% end %>
                    <th>Amount</th>
                </tr>
            </thead>

            <tbody>
                <% @user_transactions.each do |transact| %>
                        <tr>
                            <td><%= transact.date_booked.strftime("%F") %></td>
                            <td><%= transact.lesson.languageskill.language_name %></td>
                            <td><%= transact.lesson.duration %></td>
                            <% if current_user.role.privilege == "teacher" %>
                                <td><%= "#{transact.user.profile.firstname} #{transact.user.profile.lastname}" %></td>
                            <% else %>
                                <td><%= "#{transact.lesson.user.profile.firstname} #{transact.lesson.user.profile.lastname}" %></td>
                            <% end %>
                            <td><%= transact.amountpaid %></td>
                        </tr>
                <% end %>
            </tbody>
        </table>
        </div>
    </div>
  </div>

  <%= render "pages/footer_public" %>
</body>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Uploaded image</th>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Bio</th>
      <th>Skypename</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.user_id %></td>
        <td><%= profile.uploaded_image %></td>
        <td><%= profile.firstname %></td>
        <td><%= profile.lastname %></td>
        <td><%= profile.bio %></td>
        <td><%= profile.skypename %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<head>
  <title>Home | Chatr</title>
  <link rel="icon" type="image/png" href="">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>

<body>
  <%= render '/pages/header_nav_public' %>

  <div id="body" class="outer-wrapper">
    <div class="inner-wrapper">
      
      <%# PUT YOUR CONTENT HERE - THIS CONTAINER IS 1200px WIDE WITH 10px of PADDING LEFT AND RIGHT %>
        <div class= "formbox">
            <div class= "formcontent">
                <h1 id="formtitle">New Profile</h1>
                  <p id="notice"><%= notice %></p>
                <div class="formfields">
                    <%= render 'form', profile: @profile %>
                </div>
            </div>
        </div>
    </div>
      
  </div>

  <%= render "pages/footer_public" %>
</body>

app/views/profiles/show.html.erb
<head>
  <title>Profile | Chatr</title>
  <link rel="icon" type="image/png" href="">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>

<body>
  <!-- MAIN NAVIGATION | START -->
  <% if current_user %>
    <%= render '/pages/header_nav_authenticated' %>
  <% else %>
    <%= render '/pages/header_nav_public' %>
  <% end %> <!-- MAIN NAVIGATION | END -->

  <!-- USER PROFILE OUTER WRAPPER | START -->
  <div id="body" class="user-profile outer-wrapper">
    <!-- PROFILE COVER IMAGE START -->
    <div class="profile-cover-image">
      <% if @profile.background_image.attached? %>
        <%= image_tag @profile.background_image.service_url %>
      <% end %>
    </div> <!-- PROFILE COVER IMAGE END -->
    <div class="profile-inner-wrapper"> <!-- INNER WRAPPER | START -->
      <!-- PROFILE COLUMN 1 (LEFT) START -->
      <div class="profile-col-1">
        <div class="profile-picture">
          <%= image_tag @profile.uploaded_image.service_url %>
        </div>
        <div class="profile-row profile-firstname-lastname">
          <span> <%= @profile.firstname %> <%= @profile.lastname %> </span>
        </div>
        <div class="profile-row profile-user-rating">
          <% if @user.role.privilege == "teacher"%>
            <% @user.profile.average_rating.to_i.times do  %>
              <span class="glyphicon glyphicon-star"></span>
            <% end %>
            <% if @user.profile.average_rating.to_i != 5 || @user.profile.average_rating.to_i != nil %>
              <% (5 - @user.profile.average_rating.to_i).times do %>
              <span class="glyphicon glyphicon-star-empty"></span>
              <% end %>
            <% end %>
          <% end %>
        </div>
        <div class="profile-row profile-title">
          <span> <i class="fas fa-info-circle"></i> About <%= @profile.firstname %> </span>
        </div>
        <div class="profile-row profile-info">
            <span> <%= @profile.bio %> </span>
        </div>
        <div class="profile-row profile-title">
          <span> <i class="fab fa-skype"></i> Skype <%= @profile.firstname %> </span>
        </div>
        <div class="profile-row profile-info">
            <span> <%= @profile.skypename %> </span>
        </div>
        <div class="profile-row profile-title">
          <span> <i class="fas fa-volume-up"></i> Languages Spoken </span>
        </div>
        <div class="profile-row profile-info">
          <% @user.profile.languageskills.each do |languageskill| %>
            <div class="profile-info-languages-spoken">
              <div class="languages-spoken-left">
                <span style="font-weight: 500;"> Language:&nbsp;</span> <span style="font-style: italic;"> <%= languageskill.language_name %> </span>
              </div>
              <div class="languages-spoken-divider">
                  | 
              </div>
              <div class="languages-spoken-right"> 
                <span style="font-weight: 500;"> Proficiency:&nbsp;</span> <span style="font-style: italic;"> <%= languageskill.proficiency %> </span>
              </div>
            </div>
          <%end%>
        </div>
        <% if @user.role.privilege == "teacher" %>
          <div class="profile-row profile-title">
            <span> <i class="fas fa-graduation-cap"></i> Languages Taught </span>
          </div>
          <div class="profile-row profile-info">
            <span>
                <% @user.profile.languageskills.each do |languageskill| %>
                  <div class="profile-info-languages-spoken">
                    <% if languageskill.teaches%>
                      <span style="font-weight: 500;"> Language:&nbsp;</span>
                      <span style="font-style: italic;"> <%= languageskill.language_name %> </span>
                    <% end %>
                  </div>
                <% end %>
            </span>
          </div>
         <% end %>
        <div class="profile-row profile-buttons">
          <% if @user.profile.id == current_user.profile.id %>
            <%= link_to '<i class="fas fa-edit"></i> edit profile'.html_safe, edit_profile_path(@profile), class:"edit-profile-btn" %>
          <% end %>
          <% if @user.profile.id == current_user.profile.id && @user.role.privilege == "teacher" %>
            <%= link_to '<i class="fas fa-arrow-alt-circle-left"></i> add language'.html_safe, new_languageskill_path, class:"add-language-btn" %>
            <%= link_to '<i class="fas fa-edit"></i> add lesson'.html_safe, new_lesson_path, class:"add-lesson-btn" %>
          <% elsif @user.profile.id != current_user.profile.id && current_user.role.privilege != "teacher" %>
            <%= button_to('send message', "/conversations", params: {:conversation => {:user1_id => current_user.id, :user2_id => @user} }, :method => :post)%>
          <% end %>
        </div>
      </div> <!-- PROFILE COLUMN 1 (LEFT) END -->
      <!-- PROFILE COLUMN 2 (RIGHT) START -->
      <div class="profile-col-2">
        <div class="profile-col-2-container">
          <%if @user.role.privilege == "teacher"%>
            <% if params[:reviews] == "1" %>
              <%= render partial: 'reviews_profile', locals: {user: @user, user_reviews: @user_reviews, profile: @profile}%>
            <% else %>
              <%= render partial: 'lessons_profile'%>
            <% end %>
          <%end%>
          <%if @user.role.privilege == "student"%>
            <%= render partial: 'student_about_me', locals: {user: @user, profile: @profile}%>
          <%end%>
        </div>
      </div> <!-- PROFILE COLUMN 2 (RIGHT) END -->
    </div> <!-- INNER WRAPPER | END -->
  </div> <!-- USER PROFILE OUTER WRAPPER | END -->
  <!-- FOOTER NAVIGATION | START -->
  <%= render '/pages/footer_public' %><!-- FOOTER NAVIGATION | END -->
</body>