config/routes.rb
Rails.application.routes.draw do
  resources :replies
  resources :reviews
  resources :userbookings
  resources :conversations
  resources :messages
  resources :lessons
  resources :languageskills
  resources :profiles
  resources :notifications
  devise_for :users
  put '/userbookings/completelesson/:id', to: 'userbookings#completelesson'
  root to: 'pages#landing'
  get '/browse', to: 'pages#index'
  get '/browse/lessons', to: 'pages#browse_lessons'
  post '/browse/lessons', to: 'pages#browse_lessons'
  get '/browse/teachers', to: 'pages#browse_teachers'
  post '/browse/teachers', to: 'pages#browse_teachers'
  get '/userbookings/:id/review', to: 'reviews#new'
  resources :charges
  get '/finances', to: 'profiles#finances'
  post '/profile/:id/delist-lesson', to: 'profiles#delist_lesson'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :user1, :class_name => "User"
	belongs_to :user2, :class_name => "User"
	has_many :messages, dependent: :destroy
end

app/models/languageskill.rb
class Languageskill < ApplicationRecord
    belongs_to :profile, optional: true
    has_many :lessons
    validates :proficiency, :inclusion => { :in => 0..10 }
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :languageskill
  has_many :userbookings
  belongs_to :user

  scope :lessons_by_language, -> (language) { joins(:languageskill).where('language_name = ?', language) }

end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :conversation
    belongs_to :author, :class_name => "User"
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user 
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user, optional: true
  has_one_attached :uploaded_image
  has_one_attached :background_image
  has_many :languageskills, dependent: :destroy

  validates :firstname, :lastname, :bio, :skypename, :presence => {:message => "Please fill out this field"}

  def update_average_rating
    set_average_rating
  end

  private
  def set_average_rating
    teacher = User.find(self.user_id)
    userbookings_with_review = 0
    total_stars = 0
    teacher.lessons.each do |lesson|
      lesson.userbookings.each do |userbooking|
        if(userbooking.review)
          userbooking_stars = userbooking.review.stars
          total_stars += userbooking_stars
          userbookings_with_review += 1
        end
      end
    end
    if(userbookings_with_review != 0)
      self.average_rating = ((total_stars / (userbookings_with_review * 5.0)) * 5).round
      self.save!
    end
  end
  
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :review
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :userbooking
  has_one :reply, dependent: :destroy
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :conversations
	belongs_to :role, optional: true
	has_many :notifications
  has_one :profile
  has_many :userbookings
  has_many :messages
  has_many :lessons

  # validates :email, uniqueness: true
  
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable  

  scope :teachers_by_firstname, -> (firstname) { joins(:profile).where('firstname = ?', firstname) }

end

app/models/userbooking.rb
class Userbooking < ApplicationRecord
  belongs_to :user
  belongs_to :lesson
  has_one :review, dependent: :destroy
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification}
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification}
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:user_id, :seen, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/userbookings_helper.rb
module UserbookingsHelper
end

app/views/notifications/_form.html.erb
<%= form_with(model: notification, local: true) do |form| %>
  <% if notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :seen %>
    <%= form.text_field :seen %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notifications</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Seen</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= notification.user %></td>
        <td><%= notification.seen %></td>
        <td><%= notification.content %></td>
        <td><%= link_to 'Show', notification %></td>
        <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
        <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @notification.user %>
</p>

<p>
  <strong>Seen:</strong>
  <%= @notification.seen %>
</p>

<p>
  <strong>Content:</strong>
  <%= @notification.content %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>