config/routes.rb
Rails.application.routes.draw do
  resources :replies
  resources :reviews
  resources :userbookings
  resources :conversations
  resources :messages
  resources :lessons
  resources :languageskills
  resources :profiles
  resources :notifications
  devise_for :users
  put '/userbookings/completelesson/:id', to: 'userbookings#completelesson'
  root to: 'pages#landing'
  get '/browse', to: 'pages#index'
  get '/browse/lessons', to: 'pages#browse_lessons'
  post '/browse/lessons', to: 'pages#browse_lessons'
  get '/browse/teachers', to: 'pages#browse_teachers'
  post '/browse/teachers', to: 'pages#browse_teachers'
  get '/userbookings/:id/review', to: 'reviews#new'
  resources :charges
  get '/finances', to: 'profiles#finances'
  post '/profile/:id/delist-lesson', to: 'profiles#delist_lesson'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :user1, :class_name => "User"
	belongs_to :user2, :class_name => "User"
	has_many :messages, dependent: :destroy
end

app/models/languageskill.rb
class Languageskill < ApplicationRecord
    belongs_to :profile, optional: true
    has_many :lessons
    validates :proficiency, :inclusion => { :in => 0..10 }
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :languageskill
  has_many :userbookings
  belongs_to :user

  scope :lessons_by_language, -> (language) { joins(:languageskill).where('language_name = ?', language) }

end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :conversation
    belongs_to :author, :class_name => "User"
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user 
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user, optional: true
  has_one_attached :uploaded_image
  has_one_attached :background_image
  has_many :languageskills, dependent: :destroy

  validates :firstname, :lastname, :bio, :skypename, :presence => {:message => "Please fill out this field"}

  def update_average_rating
    set_average_rating
  end

  private
  def set_average_rating
    teacher = User.find(self.user_id)
    userbookings_with_review = 0
    total_stars = 0
    teacher.lessons.each do |lesson|
      lesson.userbookings.each do |userbooking|
        if(userbooking.review)
          userbooking_stars = userbooking.review.stars
          total_stars += userbooking_stars
          userbookings_with_review += 1
        end
      end
    end
    if(userbookings_with_review != 0)
      self.average_rating = ((total_stars / (userbookings_with_review * 5.0)) * 5).round
      self.save!
    end
  end
  
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :review
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :userbooking
  has_one :reply, dependent: :destroy
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :conversations
	belongs_to :role, optional: true
	has_many :notifications
  has_one :profile
  has_many :userbookings
  has_many :messages
  has_many :lessons

  # validates :email, uniqueness: true
  
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable  

  scope :teachers_by_firstname, -> (firstname) { joins(:profile).where('firstname = ?', firstname) }

end

app/models/userbooking.rb
class Userbooking < ApplicationRecord
  belongs_to :user
  belongs_to :lesson
  has_one :review, dependent: :destroy
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  # GET /lessons
  # GET /lessons.json
  def index
    authorize(Lesson)
    @lessons = Lesson.all
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
    authorize(Lesson)
  end

  # GET /lessons/new
  def new
    authorize(Lesson)
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
    authorize(Lesson)
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)
    authorize(Lesson)
    @profile = @lesson.user.profile
  
    if @lesson.save
      redirect_to profile_path @profile
    else
      render 'new'
    end

    # find the languageskill associated with the newly created lesson
    language_skill = Languageskill.where("id = ?", params[:lesson][:languageskill_id])[0]
    # set the languageskill teaches field to true
    language_skill.teaches = true
    language_skill.save!
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    authorize(Lesson)
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to request.headers[“HTTP_REFERER”]}
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    authorize(Lesson)
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params.require(:lesson).permit(:user_id, :languageskill_id, :price, :duration, :description, :maxbooking)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    before_action :set_lessons
    before_action :set_teachers
    
    def landing
    end

    def index
        set_lesson_card_array(@lessons)
        set_teachers_card_array(@teachers)
    end

    def browse_lessons 
        @lessons = Lesson.lessons_by_language(params[:search_lang]) if params[:search_lang].present?
        set_lesson_card_array(@lessons)
    end

    def browse_teachers
        @teachers = User.teachers_by_firstname(params[:search_teach_firstname]) if params[:search_teach_firstname].present?
        set_teachers_card_array(@teachers)
    end

    private
    def set_lessons
        @lessons = Lesson.all
    end

    def set_lesson_card_array(lessons)
        @lesson_card_array = []
        lessons.each do |lesson|
            lesson_card_info = {
                language: lesson.languageskill.language_name, 
                duration: lesson.duration, 
                maxbooking: lesson.maxbooking, 
                description: lesson.description,
                teacher_name:lesson.user.profile.firstname,
                teacher_profile:lesson.user.profile,
                teacher_id:lesson.user_id,
                price:lesson.price,
                id: lesson.id,    
                profilepic: lesson.user.profile.uploaded_image
            }
            @lesson_card_array << lesson_card_info
        end
    end

    def set_teachers
        @teachers = User.where(role: Role.second)
    end

    def set_teachers_card_array(teachers)
        @teachers_card_array = []
        teachers.each do |teacher|
            languageskills_arr = teacher.profile.languageskills
            languages = []
            languageskills_arr.each do |languageskill|
                if(languageskill.teaches == true)
                languages << languageskill.language_name
                end
            end

            teacher_card_info = {
                :profile_id => teacher.profile.id,
                :name => teacher.profile.firstname,
                :bio => teacher.profile.bio,
                :teach_languages => languages,
                :stars => teacher.profile.average_rating,
                :image => teacher.profile.uploaded_image
            }
            @teachers_card_array << teacher_card_info
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/userbookings_helper.rb
module UserbookingsHelper
end

app/views/lessons/_form.html.erb
<%= form_with(model: lesson, local: true) do |form| %>
  <% if lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
      <% lesson.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :user_id, value: "#{current_user.id}" %>
  </div>

  <div class="field">
    <%= form.label "Price $", :class => "labels" %>
    <%= form.number_field :price, :class => "textbox", :min => 0, :required => true%>
  </div>

  <div class="field">
    <%= form.label "Duration in minutes", :class => "labels" %>
    <%= form.number_field :duration, :class => "textbox", :min => 0, :max => 180, :required => true %>
  </div>

  <div class="field">
    <%= form.label "Language", :class => "labels"%>
    <%= form.select(:languageskill_id, current_user.profile.languageskills.all.collect {|lang|[lang.language_name, lang.id]}, :required => true) %>
  </div>

  <div class="field">
    <%= form.label "Description", :class => "labels"%>
    <%= form.text_area :description, :class => "resizable-textboxes", :placeholder => "Write a short description of your lesson here. Include a short blurb of your teaching style and what level of learner this lesson is best suited to.", :required => true %>
  </div>

  <div class="field">
    <%= form.label "How many of this lesson would you like to make available for purchase?", :class => "labels" %>
    <%= form.number_field :maxbooking, :class => "textbox" %>
  </div>

  <div class="submit-actions">
    <%= form.submit 'publish lesson', :id => "submit-button"%>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<h1>Editing Lesson</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

app/views/lessons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lessons</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Price</th>
      <th>Language</th>
      <th>Duration</th>
      <th>Description</th>
      <th>Maxbooking</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td>user_id: <%= lesson.user_id %>, lesson_id: <%=lesson.id%></td>
        <td><%= lesson.price %></td>
        <td><%= lesson.languageskill %></td>
        <td><%= lesson.duration %></td>
        <td><%= lesson.description %></td>
        <td><%= lesson.maxbooking %></td>
        <td><%= link_to 'Show', lesson %></td>
        <td><%= link_to 'Edit', edit_lesson_path(lesson) %></td>
        <td><%= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lesson', new_lesson_path %>

app/views/lessons/new.html.erb
<head>
  <title>Home | Chatr</title>
  <link rel="icon" type="image/png" href="">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>

<body>
  <% if current_user %>
    <%= render '/pages/header_nav_authenticated' %>
  <% else %>
    <%= render '/pages/header_nav_public' %>
  <% end %>

  <div id="body" class="outer-wrapper">
    <div class="inner-wrapper">
      
      <%# PUT YOUR CONTENT HERE - THIS CONTAINER IS 1200px WIDE WITH 10px of PADDING LEFT AND RIGHT %>
        <div class="formbox">
            <div class = "formcontent">
                <h1 id = "formtitle">New Lesson</h1>
                <div class = "formfields">
                    <%= render 'form', lesson: @lesson %>
                </div>
            </div>
        </div>
    </div>
      
  </div>

  <%= render "pages/footer_public" %>
</body>

app/views/lessons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @lesson.user_id %>
</p>

<p>
  <strong>Price:</strong>
  <%= @lesson.price %>
</p>


<p>
  <strong>Language:</strong>
  <%= @lesson.languageskill %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @lesson.duration %>
</p>

<p>
  <strong>Description:</strong>
  <%= @lesson.description %>
</p>

<p>
  <strong>Maxbooking:</strong>
  <%= @lesson.maxbooking %>
</p>

<%= link_to 'Edit', edit_lesson_path(@lesson) %> |
<%= link_to 'Back', lessons_path %>