config/routes.rb
Rails.application.routes.draw do
  resources :replies
  resources :reviews
  resources :userbookings
  resources :conversations
  resources :messages
  resources :lessons
  resources :languageskills
  resources :profiles
  resources :notifications
  devise_for :users
  put '/userbookings/completelesson/:id', to: 'userbookings#completelesson'
  root to: 'pages#landing'
  get '/browse', to: 'pages#index'
  get '/browse/lessons', to: 'pages#browse_lessons'
  post '/browse/lessons', to: 'pages#browse_lessons'
  get '/browse/teachers', to: 'pages#browse_teachers'
  post '/browse/teachers', to: 'pages#browse_teachers'
  get '/userbookings/:id/review', to: 'reviews#new'
  resources :charges
  get '/finances', to: 'profiles#finances'
  post '/profile/:id/delist-lesson', to: 'profiles#delist_lesson'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/userbooking.rb
class Userbooking < ApplicationRecord
  belongs_to :user
  belongs_to :lesson
  has_one :review, dependent: :destroy
end

app/controllers/userbookings_controller.rb
class UserbookingsController < ApplicationController
  before_action :set_userbooking, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:index, :show, :edit, :update, :destroy]

  # GET /userbookings
  # GET /userbookings.json
  def index
    authorize(Userbooking)
    if current_user.role.privilege == "student"
      @all_userbooking_cards = [[],[]]
      userbookings = Userbooking.all.where(user_id: current_user.id)
      userbookings.each do |booking|
        card_information = {
          userbooking: booking,
          picture: booking.lesson.user.profile,
          teacher: booking.lesson.user.profile.firstname,
          language: booking.lesson.languageskill.language_name,
          date: booking.date_booked,
          note: booking.note,
          description: booking.lesson.description,
          duration: booking.lesson.duration,
          complete: booking.completedstu
        }
        if card_information[:complete] == true
          @all_userbooking_cards[1] << card_information
        else 
          @all_userbooking_cards[0] << card_information
        end
      end
    else
      @all_userbooking_cards = [[],[]]
      Userbooking.all.each do |booking|
        if booking.lesson.user_id == current_user.id
          card_information = {userbooking: booking,
            picture: booking.user.profile,
            teacher: booking.lesson.user.profile.firstname,
            language: booking.lesson.languageskill.language_name,
            date: booking.date_booked,
            note: booking.note,
            description: booking.lesson.description,
            duration: booking.lesson.duration,
            complete: booking.completedstu,
            review: booking.review,
            student: booking.user.profile.firstname,
            student_profile: booking.user.profile
          }
          if card_information[:complete] == true
            @all_userbooking_cards[1] << card_information
          else
            @all_userbooking_cards[0] << card_information
          end
        end
      end
    puts @all_userbooking_cards
    end
  end
  # GET /userbookings/1
  # GET /userbookings/1.json
  def show
    authorize(Userbooking)
  end

  def completelesson
    authorize(Userbooking)
    userbooking = Userbooking.find(params[:id])
    userbooking.completedstu = true
    userbooking.save!
    redirect_to request.headers["HTTP_REFERER"]
  end

  # GET /userbookings/new
  def new
    authorize(Userbooking)
    @userbooking = Userbooking.new
    @lesson = Lesson.find(params[:lesson_id])
  end

  # GET /userbookings/1/edit
  def edit
    authorize(Userbooking)
  end

  # POST /userbookings
  # POST /userbookings.json
  def create
    @userbooking = Userbooking.new(userbooking_params)
    authorize(Userbooking)
    @lesson = @userbooking.lesson
    if(@lesson.maxbooking != 0)
      
      respond_to do |format|
        if @userbooking.save
          format.html { redirect_to userbookings_path, notice: 'Your lesson was was successfully booked!' }
          format.json { render :show, status: :created, location: @userbooking }
        else
          format.html { render :new }
          format.json { render json: @userbooking.errors, status: :unprocessable_entity }
        end
      end
      # decrement maxbooking on lesson each time a new userbooking is created for that lesson
      decrement_lesson_maxbooking(@lesson)
    end
  end

  # PATCH/PUT /userbookings/1
  # PATCH/PUT /userbookings/1.json
  def update
    authorize(Userbooking)
    respond_to do |format|
      if @userbooking.update(userbooking_params)
        format.html { redirect_to request.headers["HTTP_REFERER"], notice: 'Userbooking was successfully updated.' }
        format.json { render :show, status: :ok, location: @userbooking }
      else
        format.html { render :edit }
        format.json { render json: @userbooking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /userbookings/1
  # DELETE /userbookings/1.json
  def destroy
    authorize(Userbooking)
    @userbooking.destroy
    respond_to do |format|
      format.html { redirect_to userbookings_url, notice: 'Userbooking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = current_user
    end

    def set_userbooking
      @userbooking = Userbooking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def userbooking_params
      params.require(:userbooking).permit(:user_id, :lesson_id, :note, :date_booked, :completedstu, :completedteach, :amountpaid)
    end

    def decrement_lesson_maxbooking(lesson)
      lesson.maxbooking -= 1
      lesson.save!
    end
end

app/helpers/userbookings_helper.rb
module UserbookingsHelper
end

app/views/userbookings/_form.html.erb
<%= form_with(model: userbooking, local: true) do |form| %>
    <div class="formstats">
      <% @lesson = Lesson.find(params[:lesson_id]) %>
      <p> <%= @lesson.languageskill.language_name %> with <%= @lesson.user.profile.firstname %> |</p> 
      <p>$<%= @lesson.price %> | </p> 
      
      <p> <%= @lesson.duration %> minutes </p>
    </div>

    <% if userbooking.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(userbooking.errors.count, "error") %> prohibited this userbooking from being saved:</h2>

        <ul>
        <% userbooking.errors.full_messages.each do |message| %> 
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= form.hidden_field :user_id, value: "#{current_user.id}"%>
    </div>

    <div class="field">
      <%= form.hidden_field :lesson_id, value: params[:lesson_id]%>
    </div>

    <div class="field">
      <%= form.hidden_field :amountpaid, value: @lesson.price%>
    </div>

    <div class="field">
      <%= form.label :note, :class => "labels" %>
      <%= form.text_area :note, :class => "resizable-textboxes", :required => true%>
    </div>

    <div class="field dateselect">
      <%= form.label :date_booked, :class => "labels" %>
      <%= form.date_field :date_booked, selected: Date.today, min: Date.new(Time.new.year, Time.new.month, Time.new.day), max: 1.year.from_now, :required => true %>
    </div>

    <div class="submit-actions">
      <%= form.submit 'Confirm Booking', :name => 'Confirm Booking', :id => "submit-button"%>
    </div>
<% end %>

<script>
  var dates = document.querySelector('.dateselect')
  var nodes = dates.childNodes
  nodes[8].remove()
  nodes[9].remove()
</script>

app/views/userbookings/_teacherbooking_card.html.erb
<% @all_userbooking_cards %>

<div class="rowofcards rowofcards-outer">
    <div class="cardslider icon scroll-arrow-teachers">
        <% @all_userbooking_cards[locals[:completed]].each do |cardinfo|%>
            <div class="card" id="bookingcard">

                <div class="titlesection">
                    <% if cardinfo[:picture].uploaded_image.attached? %>
                        <%= link_to "/profiles/#{cardinfo[:student_profile].id}" do %>
                            <%= image_tag (cardinfo[:picture].uploaded_image), class: 'profilepic-image' %>
                        <% end %>
                    <% else %>
                        <i id="browse-pages" class="fas fa-user"></i>
                    <% end %>
                    
                    <div class="righthandside">
                        <h2 id = "langwithteach"> <%= "#{cardinfo[:language]} with #{cardinfo[:student]}" %> </h2>
                        <div class = "subtitlesection">
                            <span class="glyphicon glyphicon-hourglass"></span>
                            <%= "#{cardinfo[:duration]} minutes | #{cardinfo[:date].strftime("%e %B, %Y")}"%>
                        </div>
                    </div> 

                </div>

                <div class = "cardbody">
                    <div id = "subtitle"> <strong> Lesson description: </strong> <%= "#{cardinfo[:description]}" %> </div> 

                    <div id = "subtitle"> <strong> Your note from  <%= "#{cardinfo[:student]}:" %> </strong> <%= "#{cardinfo[:note]}" %> </div> 
                </div>
                
                <div class = "bottombar">
                    <div class = "button" >
                        <%= link_to "contact #{cardinfo[:student]}",new_conversation_path %>
                    </div>

                    <div id = "complete" class = "complete?">
                        <% if cardinfo[:review] != nil %>
                            <div id = "review-content"> <strong> Review available: </strong> <%= "#{cardinfo[:review].content}" %> </div> 
                            <% if cardinfo[:userbooking].review.reply == nil %>
                                <%= link_to "reply", new_reply_path(:id => cardinfo[:userbooking].id) %>
                            <% else %>
                                <div id = "subtitle"> You have already replied. </div>
                            <% end %>
                        <% else %>
                            <div id = "subtitle"> <strong> Review not yet available </strong> </div> 
                        <% end %>
                    </div>
                </div>
                
            </div>
        <% end %>
    </div>
</div>

app/views/userbookings/_userbooking_card.html.erb
<% @all_userbooking_cards %>

<div class="rowofcards rowofcards-outer">
    <div class="cardslider icon scroll-arrow-teachers">
        <% @all_userbooking_cards[locals[:completed]].each do |cardinfo|%>
            <div class="card" id="bookingcard">

                <div class="titlesection">
                    <% if cardinfo[:picture].uploaded_image.attached? %>
                        <%= image_tag cardinfo[:picture].uploaded_image, class: 'profilepic-image' %>
                    <% else %>
                        <i id="browse-pages" class="fas fa-user"></i>
                    <% end %> 
                    
                    <div class="righthandside">
                        <h2 id = "langwithteach"> <%= "#{cardinfo[:language]} with #{cardinfo[:teacher]}" %> </h2>
                        <div class = "subtitlesection">
                            <span class="glyphicon glyphicon-hourglass"></span>
                            <%= "#{cardinfo[:duration]} minutes | #{cardinfo[:date].strftime("%e %B, %Y")}"%>
                        </div>
                    </div>

                </div>

                <div class = "cardbody">
                    <div id = "subtitle"> <strong> Your note to <%= "#{cardinfo[:teacher]}:" %> </strong> <%= "#{cardinfo[:note]}" %> </div> 

                    <div id = "subtitle"> <strong> Lesson description: </strong> <%= "#{cardinfo[:description]}" %> </div> 
                </div>
                
                <div class = "bottombar">
                    <div class = "button" >
                        <%= link_to "CONTACT #{cardinfo[:teacher].upcase}",new_conversation_path %>
                    </div>

                    <div class = "complete?">
                        <% if cardinfo[:complete] == false %>
                            <%= link_to "MARK AS COMPLETE", "/userbookings/completelesson/#{cardinfo[:userbooking].id}", method: :put%>
                        <% else %>
                            <% if cardinfo[:userbooking].review == nil %>
                                <%= link_to "REVIEW", "/userbookings/#{cardinfo[:userbooking].id}/review" %>
                            <% else %>
                                <div id = "review-content"> <strong> Review available: </strong> <%= "#{cardinfo[:userbooking].review.content}" %> </div>
                                
                                <% if cardinfo[:userbooking].review.reply == nil %>
                                    <div id = "subtitle"> <strong> Reply not yet available </strong> </div> 
                                <% else %>
                                    <div id = "review-content"> <strong> Teacher Reply: </strong> <%= "#{cardinfo[:userbooking].review.reply.content}" %> </div>
                                <% end %> 

                            <%end%>

                        <% end %>
                    </div>
                </div>
                
            </div>
        <% end %>
    </div>
</div>

app/views/userbookings/edit.html.erb
<h1>Editing Userbooking</h1>

<%= render 'form', userbooking: @userbooking %>

<%= link_to 'Show', @userbooking %> |
<%= link_to 'Back', userbookings_path %>

app/views/userbookings/index.html.erb
<head>
  <title>Home | Chatr</title>
  <link rel="icon" type="image/png" href="">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>

<body>
  <% if current_user %>
    <%= render '/pages/header_nav_authenticated' %>
  <% else %>
    <%= render '/pages/header_nav_public' %>
  <% end %>

  <div id="body" class="outer-wrapper">
    <div class="inner-wrapper">
      <div class = "cardwrapper">
        <% if current_user.role.privilege == "teacher" %>
          <div class="rowofcards">
            <h1> Your upcoming bookings: </h1>
            <p id="notice"><%= notice %></p>
            <%= render 'teacherbooking_card', locals: {completed: 0}  %>
          </div>

          <div class="rowofcards">
            <h1> Your previous bookings: </h1>
            <%= render 'teacherbooking_card', locals: {completed: 1} %>
          </div>
        <% else %>
          <div class="rowofcards">
            <h1> Your upcoming bookings: </h1>
            <p id="notice"><%= notice %></p>
            <%= render 'userbooking_card', locals: {completed: 0}  %>
          </div>

          <div class="rowofcards">
            <h1> Your previous bookings: </h1>
            <%= render 'userbooking_card', locals: {completed: 1} %>
          </div>
        <% end %>
      </div>

    </div>
  </div>

  <%= render "pages/footer_public" %>
</body>

app/views/userbookings/new.html.erb
<head>
  <title>Home | Chatr</title>
  <link rel="icon" type="image/png" href="">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>

<body>
  <% if current_user %>
    <%= render '/pages/header_nav_authenticated' %>
  <% else %>
    <%= render '/pages/header_nav_public' %>
  <% end %>

  <div id="body" class="outer-wrapper">
    <div class="inner-wrapper">
      
      <%# PUT YOUR CONTENT HERE - THIS CONTAINER IS 1200px WIDE WITH 10px of PADDING LEFT AND RIGHT %>

    <div class="formbox">
    <div class = "formcontent">

        <h1 id="formtitle">New Booking</h1>
            <div class= "formfields">
                <%= render 'form', userbooking: @userbooking %>

                <%= render partial: "layouts/shared/stripe_form" %>
            </div>

            
            <script>
                var stripe = document.querySelector(".custom-stripe-button")

                var submitbutton = document.querySelector("#submit-button")

                submitbutton.style.display = 'none';
                
                stripe.addEventListener('click', () => {
                  submitbutton.style.display = 'block';
                })
            </script>
           
        </div>
    </div>
      
  </div>

  <%= render "pages/footer_public" %>
</body>

app/views/userbookings/show.html.erb
<head>
  <title>Home | Chatr</title>
  <link rel="icon" type="image/png" href="">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>

<body>
  <% if current_user %>
    <%= render 'pages/header_nav_authenticated' %>
  <% else %>
    <%= render 'pages/header_nav_public' %>
  <% end %>

  <div id="body" class="outer-wrapper">
    <div class="inner-wrapper">
       
      <p id="notice"><%= notice %></p>

      <p>
        <strong>Student:</strong>
        <%= @userbooking.user %>
      </p>

      <p>
        <strong>Lesson:</strong>
        <%= @userbooking.lesson %>
      </p>

      <p>
        <strong>Note:</strong>
        <%= @userbooking.note %>
      </p>

      <p>
        <strong>Date booked:</strong>
        <%= @userbooking.date_booked %>
      </p>

      <p>
        <strong>Completedstu:</strong>
        <%= @userbooking.completedstu %>
      </p>

      <%= link_to 'Edit', edit_userbooking_path(@userbooking) %> |
      <%= link_to 'Back', userbookings_path %>    
      
    </div>
  </div>

  <%= render "pages/footer_public" %>
</body>